### ISSUE TITLE
Rate Limit Exceeded error: Display for how long users should wait

### ISSUE THREAD

**Issue by payne911** [useful-forks/useful-forks.github.io#14]
When the `403 - Rate Limit Exceeded` error happens, one of the headers is `x-ratelimit-reset: 1614575718`. The digit is a UNIX Timestamp which [could be converted](https://www.epochconverter.com/) to display how long the user should wait before trying again.

**Comment by payne911** [comment]
Closing this issue with a new feature to celebrate this repo's 800th star! :)

![image](https://user-images.githubusercontent.com/38117856/205836876-c2809452-4c41-4e33-96fe-c03eeed101d4.png)

**Comment by shashankYelluri** [comment]
Hey @payne911, how did you solve this issue? 
I encountered the same situation where I had to wait for some "x" time before making a request. But the throttle plugin added 5 seconds, is there a way to change this ?
If possible, could you please help me with this?
Thanks

**Comment by payne911** [comment]
> I encountered the same situation where I had to wait for some "x" time before making a request. But the throttle plugin added 5 seconds, is there a way to change this ?

You mean that the plugin ignores the "x" and always only waits for 5 seconds?

Does this help? https://github.com/octokit/plugin-throttling.js/issues/454#issuecomment-1374903573
