### ISSUE TITLE
When user is prompted for a token, and it is given, use it

### ISSUE THREAD

**Issue by stdedos** [useful-forks/useful-forks.github.io#29]
If the user is prompted for a token, and it is given (saved), either:
* Resume scanning, or
* At least re-activate the scan button

**Comment by payne911** [comment]
Oh, I indeed didn't test that flow much. I'll look into it. Thank you for reporting it!

**Comment by payne911** [comment]
I pre-emptively pushed. I'm currently fixing what I did.

**Comment by payne911** [comment]
@stdedos let me know if you find anything abnormal which relates to this specific flow.

**Comment by stdedos** [comment]
Verified as fixed :-D
