### ISSUE TITLE
Please add last commit date

### ISSUE THREAD

**Issue by edo1** [useful-forks/useful-forks.github.io#32]
It would be useful to see when the last commit was made.

Even better would be to see the date of the last upstream commit as well, because "70 commits behind" say nothing about dates. But not sure how difficult it will be.

**Comment by payne911** [comment]
I might add it as an option (through the gear icon). I don't think it'll be available by default because I think it'll require an extra API call (which are already quite limited).

**Comment by payne911** [comment]
> maybe it makes sense to get the dates of the fork by an explicit request? (button or something like that)

Not a bad idea. I'll consider it.

**Comment by payne911** [comment]
Turns out the `pushed_at` data was already part of many of the requests the tool was already issuing.

Thanks for making this great suggestion! :)

**Comment by payne911** [comment]
See #35 for a small related update/improvement. :)
