### ISSUE TITLE
[Feature request] Allow filter dates

### ISSUE THREAD

**Issue by Aokromes** [useful-forks/useful-forks.github.io#37]
how about allow search only forks updated the last 1 day / 1 week / 1 month / 1 year / custom?

**Comment by payne911** [comment]
That's a good idea. I would have to think about how I would integrate that into the UI.

However, keep in mind I'll unfortunately be busy with other things until October, most probably, though.

**Comment by takos22** [comment]
There could be a filter to every column, like if I only want forks that are no commits behind and at least 10 commits ahead.

**Comment by payne911** [comment]
> There could be a filter to every column

I think this would be the best approach. It would ultimately unclog the "Settings" dialog which itself could be used for some more complex related things (for example, I have this idea about offering different scanning strategies to users, and maybe having the default be an automatic swap between strategies based on the amount of forks of the queried repo).

The right way to implement this would be to keep the entire result list in memory, and to only display a subset based on filtering preferences. The current implementation just throws away the data which doesn't meet the provided criterias, so it isn't flexible enough to support this kind of use-case.

I'd be stoked if someone wanted to work on this. :)
