### ISSUE TITLE
[Feature request] Add a link to GitHub API Token generator.

### ISSUE THREAD

**Issue by HamPoole** [useful-forks/useful-forks.github.io#40]
![image](https://user-images.githubusercontent.com/23442241/172309087-89a51843-75d2-40c9-8609-31bb839ce4e9.png)

As someone who's never used the GitHub API before, I'd like a link to https://github.com/settings/tokens in this popup message, so I can quickly find the *well hidden* page to make myself a token. 

(I'll make a PR in the next few days, just writing this down).

**Comment by payne911** [comment]
Hi HamPoole,

I believe this feature [is already covered](https://github.com/useful-forks/useful-forks.github.io/blob/master/website/index.html#L117). Try clicking the "`Create`" button, it should bring you there.

I appreciate your willingness to create a PR, though.
