### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by Laith-Alayassa** [useful-forks/useful-forks.github.io#43]
The link for `open source website` in :
> Thanks to star-history's `open-source website` which I adapted for this project

leads to a 404 Github page

**Comment by payne911** [comment]
Ah, nice catch. It seems like they [recently rewrote their website to use Vue](https://github.com/bytebase/star-history/pull/99).

I'll update the link so that it points to the older version of their repo. Thanks for pointing it out! :)
