### ISSUE TITLE
[Feature request] URL parameter with queried repo

### ISSUE THREAD

**Issue by wedebe** [useful-forks/useful-forks.github.io#46]
The URL doesn't update with the queried repo, which makes bookmarking impossible.

**Comment by payne911** [comment]
Ah, interesting idea.
So your saying if you type "foo/bar" in the search field, the URL should be updated accordingly.
As a temporary work around, you can actually do that manually (e.g. https://useful-forks.github.io/?repo=foo/bar), but I do like the idea of making it automatic.
