### ISSUE TITLE
Add a link back to github

### ISSUE THREAD

**Issue by dandidums** [useful-forks/useful-forks.github.io#5]
Great tool. Thanks! I finally don't have to scroll through the giant graph where I don't know what's what. 

Quick suggestion, would be nice to add link back to the original project too. Perhaps add it at the top in the table?

**Comment by payne911** [comment]
I'm guessing that would be useful in the use-case where someone clicked a link with the `repo` URL param already set up.

It could also just be convenient in the other usual use-cases, although I believe pressing the "Back" arrow in your browser would usually just bring you back to that repo ?

Would you mind letting me know about your personal motivation ?

**Comment by payne911** [comment]
Preview of the addition: 
![image](https://user-images.githubusercontent.com/38117856/109172050-590c4f00-7750-11eb-82cd-d5cdb9e9bf35.png)


"**Queried repository**" was not there before. Clicking on that repository's link will bring you back to GitHub

**Comment by dandidums** [comment]
Thank you!

**Comment by payne911** [comment]
My pleasure. It was a good suggestion. :)
