### ISSUE TITLE
When the token is invalid, no error is shown

### ISSUE THREAD

**Issue by TheTechRobo** [useful-forks/useful-forks.github.io#51]
Instead, it shows "(1 calls)" at the top-right and no forks are displayed.

**Comment by payne911** [comment]
Actually, I noticed this seems to also happen when entering a repo which doesn't exist.
![image](https://user-images.githubusercontent.com/38117856/195152950-b1f986dc-9ab5-4a79-973b-81850ac4190c.png)

**Comment by payne911** [comment]
Celebrating my 777th star by solving this issue. :)
