### ISSUE TITLE
Listed forks should link to the "compare" page

### ISSUE THREAD

**Issue by payne911** [useful-forks/useful-forks.github.io#56]
Example link: https://useful-forks.github.io/?repo=facebook/sapling
![image](https://user-images.githubusercontent.com/38117856/214160493-c9ea405f-ff9e-43cd-b05a-663cb4a709d3.png)

I realized that when I go to explore a repository, I don't really care about the repo's landing page (e.g. landing page: https://github.com/mayhemheroes/eden).

Taking the last fork listed as an example, maybe that link should open https://github.com/facebook/sapling/compare/main...mayhemheroes:eden:main instead of https://github.com/mayhemheroes/eden

Or maybe the "`ahead`" and "`behind`" badges could be those links.

I'd love to hear some thoughts about this.

**Comment by Ethkuil** [comment]
> Or maybe the "ahead" and "behind" badges could be those links.

I prefer this way.

As for links like `author/repo`, I don't really care about what it referred to(`ahead` and `behind` can be enough), but to open the `README.md` page may be more intuitive for me.

**Comment by payne911** [comment]
> but to open the README.md page may be more intuitive for me.

I think I miscommunicated what I meant so I edited the OP. I meant the "repo's landing page" which itself displays the rendered `README.md`, along with a bunch of other info.
