### ISSUE TITLE
[Feature Request] Search by number of commits

### ISSUE THREAD

**Issue by wakaztahir** [useful-forks/useful-forks.github.io#63]
Searching with commits helps when there's a huge number of repositories that have less commits , like 10 or 20 which are easily not the best option

There was an issue for this
https://github.com/isaacs/github/issues/1206

I built a code pen for this https://codepen.io/wakaztahir/pen/YzRVzZz?editors=1000

It doesn't work properly at the moment since Github doesn't support this , It could work if a little effort could be put into it

I would also like to support maximum stars to limit displaying popular repositories that I've viewed thousand times , So repositories with many commits and less stars tend to be secret gems.

**Comment by payne911** [comment]
> I would also like to support maximum stars to limit displaying popular repositories that I've viewed thousand times

You can actually use the `s<=100` filter for that. For 'ahead' and 'behind' commits, you can also use `a` and `c` as filter keywords.

Example:
![image](https://github.com/useful-forks/useful-forks.github.io/assets/38117856/1dba3434-52c8-44f0-9add-ad06c363fd0b)

**Comment by wakaztahir** [comment]
But what if there are no forks , I just wanna search for repositories

**Comment by payne911** [comment]
Sounds like this is out of scope for useful-forks.
You might want to create your own tool that does that. :)
